In [40]:
import numpy as np

A = np.array([[2, 3], [4, 5]])
B = np.array([[1, 6], [7, 2]])

print(" Addition:\n", A + B)
print(" Subtraction:\n" , A-B)
print(" Multiplication:\n", np.dot(A, B))
print("Division:")
try:
        result = np.divide(A, B)
        print(" Division Result:\n", result)
except FloatingPointError:
    print(" Error: Division by zero or invalid value encountered!")
except Exception as e:
    print(" An unexpected error occurred:", e)
  
print(" Transpose of A:\n", A.T)
print(" Transpose of B:\n", B.T)
det = np.linalg.det(A)
print(f" Determinant: {det}")

if det == 0:
    print(" Matrix is singular (det = 0)")
else:
    A_inv = np.linalg.inv(A)
    print(" Inverse:\n", A_inv)


 Addition:
 [[ 3  9]
 [11  7]]
 Subtraction:
 [[ 1 -3]
 [-3  3]]
 Multiplication:
 [[23 18]
 [39 34]]
Division:
 Division Result:
 [[2.         0.5       ]
 [0.57142857 2.5       ]]
 Transpose of A:
 [[2 4]
 [3 5]]
 Transpose of B:
 [[1 7]
 [6 2]]
 Determinant: -2.0
 Inverse:
 [[-2.5  1.5]
 [ 2.  -1. ]]
